version: "3.5"


services:
 elasticsearch:
   container_name: temporal-elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
   environment:
     - discovery.type=single-node
     - ES_JAVA_OPTS=-Xms256m -Xmx256m
     - xpack.security.enabled=false
   networks:
     - temporal-network
   expose:
     - 9200
   volumes:
     - /var/lib/elasticsearch/data


 postgresql:
   container_name: temporal-postgresql
   image: postgres:13
   environment:
     - POSTGRES_PASSWORD=temporal
     - POSTGRES_USER=temporal
   networks:
     - temporal-network
   expose:
     - 5432
   volumes:
     - /var/lib/postgresql/data


 temporal:
   container_name: temporal
   image: temporalio/auto-setup:1.21.5
   depends_on:
     - postgresql
     - elasticsearch
   environment:
     - DB=postgresql
     - DB_PORT=5432
     - POSTGRES_USER=temporal
     - POSTGRES_PWD=temporal
     - POSTGRES_SEEDS=postgresql
     - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development-sql.yaml
     - ENABLE_ES=true
     - ES_SEEDS=temporal-elasticsearch
     - ES_VERSION=v7
     - TEMPORAL_ADDRESS=temporal:7233
     - TEMPORAL_CLI_ADDRESS=temporal:7233
   ports:
     - 7233:7233
   volumes:
     - ./dynamicconfig:/etc/temporal/config/dynamicconfig
   networks:
     - temporal-network


 temporal-admin-tools:
   container_name: temporal-admin-tools
   image: temporalio/admin-tools:1.21.5
   depends_on:
     - temporal
   environment:
     - TEMPORAL_ADDRESS=temporal:7233
     - TEMPORAL_CLI_ADDRESS=temporal:7233
   stdin_open: true
   tty: true
   networks:
     - temporal-network


 temporal-ui:
   container_name: temporal-ui
   image: temporalio/ui:2.15.0
   depends_on:
     - temporal
   environment:
     - TEMPORAL_ADDRESS=temporal:7233
     - TEMPORAL_CORS_ORIGINS=http://localhost:3000
   ports:
     - 8080:8080
   networks:
     - temporal-network


networks:
 temporal-network:
   driver: bridge


